---

- name: install docker repo
  become: yes
  copy:
    src: docker.repo
    dest: '/etc/yum.repos.d/docker.repo'

- name: install docker-engine
  become: yes
  when: ansible_os_family == 'RedHat'
  yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - docker-engine
#    - net-tools
#    - wget
#    - bind-utils
#    - iptables-services
#    - bridge-utils
#    - bash-completion

- name: create service in systemd
  template:
    src: docker.service
    dest: /usr/lib/systemd/system/docker.service
    force: no
  notify:
    - reload unit
    - restart docker

- meta: flush_handlers

- name: enable and start docker service
  become: yes
  service:
    name: docker
    enabled: yes
  notify:
    - reload unit
    - restart docker
