---

- name: copy backports list
  become: yes
  template:
    src: docker.list.j2
    dest: /etc/apt/sources.list.d/backports.list

- name: install required packages
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - gnupg2
    - apt-transport-https
    - ca-certificates

- name: install gpg key
  become: yes
  apt_key:
    keyserver: "{{ docker_engine.key_server }}"
    id: "{{ docker_engine.docker_gpg_key }}"

- name: install docker repo
  become: yes
  template:
    src: docker.list.j2
    dest: /etc/apt/sources.list.d/docker.list

- name: update the index
  become: yes
  apt:
    update_cache: yes

- name: install docker
  become: yes
  apt:
    name: docker-engine
    state: present

- name: enable and start docker service
  become: yes
  service:
    name: docker
    state: started
    enabled: yes
