---

- name: ensure the docker group is present
  group:
    name: docker
    state: present
    system: yes
  tags:
    - docker

- name: ensure vagrant is member of docker group
  user:
    name: vagrant
    groups: docker
    append: yes
  when: groups['vagrant'] is defined and inventory_hostname in groups['vagrant']
  tags:
    - docker

- name: ensure jenkins is member of docker group
  user:
    name: jenkins
    groups: docker
    append: yes
  when: groups['buildserver'] is defined and inventory_hostname in groups['buildserver']
  tags:
    - docker

- name: test if docker is installed
  command: docker
  register: dockerinstalled
  ignore_errors: True
  changed_when: False

- name: ensure pip is installed
  package:
    name: python-pip
    state: present

- block:
  - include: docker-RedHat.yml
    when: ansible_os_family == 'RedHat'
    tags:
      - docker
      - redhat

  - include: docker-Debian.yml
    when: ansible_distribution == 'Debian'
    tags:
      - docker
      - debian

  - include: docker-Ubuntu.yml
    when: ansible_distribution == 'Ubuntu'
    tags:
      - docker
      - ubuntu
  when: dockerinstalled|failed

- name: install docker client for python
  pip:
    name: docker
    state: present
  tags:
    - python
  when: docker_engine.docker_py == True

- name: ensure docker compose is installed
  pip:
    name: docker-compose
    state: present
  tags:
    - docker
