---
- name: reload unit
  become: yes
  command: systemctl daemon-reload

- name: start docker
  service:
    name: docker
    state: started
    enabled: yes
  become: yes

- name: restart docker
  become: yes
  service:
    name: docker
    state: restarted

